create table calendar_events (
    id bigint generated by default as identity
      constraint event_pkey
          primary key,
    title text not null,
    previous varchar(32) not null,
    actual varchar(32) not null,
    low varchar(32) not null,
    high varchar(32) not null,
    all_day boolean default false not null,
    disabled boolean default false not null,
    occurs_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    remotely_updated_at timestamp with time zone not null,
    remote_identity varchar(64) default '' not null
);
