create table calendar_categories (
    id bigint generated by default as identity
      constraint event_pkey
          primary key,
    name text,
    display_name text,
    description text,
    location varchar(2) not null,
    unit varchar(8) not null,
    period varchar(16) not null,
    state varchar(16) not null,
    classification varchar(16) not null,
    importance varchar(16) not null,
    currency varchar(3) not null,
    data_origin varchar(32) not null,
    origin varchar(32) not null,
    updated_at timestamp with time zone not null,
    inverted boolean,
    show_period boolean default true not null
);
